
dist: trusty
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip list & pip install -U setuptools && pip install -r requirements_test.txt && pip install -U tox-travis

script:
  - tox

after_success:
  - bash <(curl -s https://codecov.io/bash)
