# Config file for automatic testing at travis-ci.org
dist: xenial   # required for Python >= 3.7
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  matrix:
    - TOX_ENV=py37-django-111
    - TOX_ENV=py36-django-111
    - TOX_ENV=py35-django-111
    - TOX_ENV=py34-django-111
    - TOX_ENV=py27-django-111
    - TOX_ENV=py37-django-20
    - TOX_ENV=py36-django-20
    - TOX_ENV=py35-django-20
    - TOX_ENV=py34-django-20

matrix:
  fast_finish: true
  include:
    - python: "2.7"
      env: TOXENV=py27-django111
    - python: "3.4"
      env: TOXENV=py34-django111
      dist: trusty
    - python: "3.5"
      env: TOXENV=py35-django111
    - python: "3.6"
      env: TOXENV=py36-django111
    - python: "3.7"
      env: TOXENV=py37-django111

    - python: "3.4"
      env: TOXENV=py34-django20
      dist: trusty
    - python: "3.5"
      env: TOXENV=py35-django20
    - python: "3.6"
      env: TOXENV=py36-django20
    - python: "3.7"
      env: TOXENV=py37-django20

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
